### PR TITLE
fix: Remove invalid settings from Gruntfile

### LINKED ISSUE #1735: Troubleshooting PKGBUILD breakage
Can you folks help me troubleshoot the failed build on 3.3.2872.

Steps: 
 - `npm install`
 - `$(npm bin)/grunt 'linux-other'`

```
(base) ~/git/wire-desktop >>>   $(npm bin)/grunt 'linux-other'                                                               ±[●][master]
Running "clean:linux" (clean) task
>> 0 paths cleaned.

Running "update-keys" task

Running "gitinfo" task

Running "release-prod" task
Releases URL points to https://wire-app.wire.com/win/prod/ OK

Running "bundle" task

Running "electronbuilder:linux_other" (electronbuilder) task
  • electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
Warning: Configuration is invalid.
 - configuration.linux should be one of these:                                                                                            
   object { appId?, artifactName?, asar?, asarUnpack?, category?, compression?, cscKeyPassword?, cscLink?, depends?, description?, desktop?, detectUpdateChannel?, electronUpdaterCompatibility?, executableName?, extraFiles?, extraResources?, fileAssociations?, files?, forceCodeSigning?, generateUpdatesFilesForAllChannels?, icon?, maintainer?, mimeTypes?, packageCategory?, protocols?, publish?, releaseInfo?, synopsis?, target?, vendor? } | {
     "type": "null"
   }
   Options related to how build Linux targets.
   
   Details:
    * configuration.linux has an unknown property 'afterInstall'. These properties are valid:
      object { appId?, artifactName?, asar?, asarUnpack?, category?, compression?, cscKeyPassword?, cscLink?, depends?, description?, desktop?, detectUpdateChannel?, electronUpdaterCompatibility?, executableName?, extraFiles?, extraResources?, fileAssociations?, files?, forceCodeSigning?, generateUpdatesFilesForAllChannels?, icon?, maintainer?, mimeTypes?, packageCategory?, protocols?, publish?, releaseInfo?, synopsis?, target?, vendor? }
    * configuration.linux has an unknown property 'afterRemove'. These properties are valid:
      object { appId?, artifactName?, asar?, asarUnpack?, category?, compression?, cscKeyPassword?, cscLink?, depends?, description?, desktop?, detectUpdateChannel?, electronUpdaterCompatibility?, executableName?, extraFiles?, extraResources?, fileAssociations?, files?, forceCodeSigning?, generateUpdatesFilesForAllChannels?, icon?, maintainer?, mimeTypes?, packageCategory?, protocols?, publish?, releaseInfo?, synopsis?, target?, vendor? }
    * configuration.linux has an unknown property 'fpm'. These properties are valid:
      object { appId?, artifactName?, asar?, asarUnpack?, category?, compression?, cscKeyPassword?, cscLink?, depends?, description?, desktop?, detectUpdateChannel?, electronUpdaterCompatibility?, executableName?, extraFiles?, extraResources?, fileAssociations?, files?, forceCodeSigning?, generateUpdatesFilesForAllChannels?, icon?, maintainer?, mimeTypes?, packageCategory?, protocols?, publish?, releaseInfo?, synopsis?, target?, vendor? }
    * configuration.linux should be null:
      {
        "type": "null"
      }

How to fix:
1. Open https://electron.build/configuration/configuration
2. Search the option name on the page.
  * Not found? The option was deprecated or not exists (check spelling).
  * Found? Check that the option in the appropriate place. e.g. "title" only in the "dmg", not in the root.
 Use --force to continue.

Aborted due to warnings.
```

**EDIT (2)**: The following changes allow the build to continue, but aren't  a universal fix as they will break the deb stuff

```diff
diff --git a/Gruntfile.js b/Gruntfile.js
index c3fa454..64786ab 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -28,8 +28,6 @@ const PACKAGE_JSON = 'package.json';
 const INFO_JSON = 'info.json';
 
 const LINUX_SETTINGS = {
-  afterInstall: 'bin/deb/after-install.tpl',
-  afterRemove: 'bin/deb/after-remove.tpl',
   category: 'Network',
   desktop: {
     Version: '<%= info.version %>.<%= buildNumber %>',
@@ -39,7 +37,7 @@ const LINUX_SETTINGS = {
     Keywords: 'chat;encrypt;e2e;messenger;videocall',
     StartupWMClass: '<%= info.name %>',
   },
-  fpm: ['--name', 'wire-desktop'],
+  executableName: 'wire-desktop'
 };
 
 module.exports = function(grunt) {
@@ -200,8 +198,7 @@ module.exports = function(grunt) {
         options: {
           arch: grunt.option('arch') || process.arch,
           linux: {
-            ...LINUX_SETTINGS,
-            fpm: ['--name', 'wire-desktop'],
+            ...LINUX_SETTINGS
           },
           targets: [grunt.option('target') || 'dir'],
         },
```

### PR DESCRIPTION
**Pull request by ffflorian**
* This fixes #1735 by removing keys from the `linux` settings which don't belong there.
* The `Version` entry in a Gnome desktop file actually specifies the version of the Desktop Entry Specification, not the product version, see https://developer.gnome.org/desktop-entry-spec/.

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -17,26 +17,28 @@
...
 const INFO_JSON = 'info.json';
+const PACKAGE_JSON = 'package.json';
+
+const LINUX_DESKTOP = {
+  Categories: 'Network;InstantMessaging;Chat;VideoConference',
+  GenericName: '<%= info.description %>',
+  Keywords: 'chat;encrypt;e2e;messenger;videocall',
+  Name: '<%= info.name %>',
+  StartupWMClass: '<%= info.name %>',
+  Version: '1.1',
```
Comment (gregor) [inline Gruntfile.js]: ?
